// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5GVQw-z1prLm5mvCXDXgjOFDjQ5ZY5yY',
    appId: '1:423295328354:web:da5d0f8e409fe98de8b13b',
    messagingSenderId: '423295328354',
    projectId: 'contacttest-94ee5',
    authDomain: 'contacttest-94ee5.firebaseapp.com',
    storageBucket: 'contacttest-94ee5.appspot.com',
    measurementId: 'G-WVXJ903F06',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXQfWxyMwS-r2pO3-V8IBwu1oLv_s_-AA',
    appId: '1:423295328354:android:f88f33276f2a09e7e8b13b',
    messagingSenderId: '423295328354',
    projectId: 'contacttest-94ee5',
    storageBucket: 'contacttest-94ee5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdngXw_lal3B72MvP6qYcIAOIY8abKedA',
    appId: '1:423295328354:ios:a7b6e9c4d4a8c790e8b13b',
    messagingSenderId: '423295328354',
    projectId: 'contacttest-94ee5',
    storageBucket: 'contacttest-94ee5.appspot.com',
    iosBundleId: 'com.example.contacttest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdngXw_lal3B72MvP6qYcIAOIY8abKedA',
    appId: '1:423295328354:ios:a4030dbaa70f7936e8b13b',
    messagingSenderId: '423295328354',
    projectId: 'contacttest-94ee5',
    storageBucket: 'contacttest-94ee5.appspot.com',
    iosBundleId: 'com.example.contacttest.RunnerTests',
  );
}
